version: '3.6'

services:
  backend:
    image: backend
    build : ./api-backend
    container_name: backend
    ports:
      - 8888:8888
  frontend:
    image: frontend
    build : ./react-front
    container_name: frontend
    ports:
      - 3000:3000